# Generated by Django 4.1.13 on 2025-05-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoninoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=15)),
                ('fechanacimiendo', models.CharField(max_length=11)),
                ('CI', models.DecimalField(decimal_places=0, max_digits=20)),
                ('Nacionalidad', models.CharField(max_length=100)),
                ('TutorCI', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
    ]
