from django.db import models

class Nino(models.Model):
    id_nino = models.IntegerField(primary_key=True)
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    etnia_raza = models.CharField(max_length=50, blank=True)
    sexo = models.CharField(max_length=10)
    fecha_nacimiento = models.DateField()
    nacionalidad = models.CharField(max_length=50)
    domicilio = models.TextField()
    telefono = models.BigIntegerField()
    servicio_salud = models.CharField(max_length=100)
    emergencia_movil = models.CharField(max_length=100)

class Embarazo(models.Model):
    id_nino = models.OneToOneField(Nino, on_delete=models.CASCADE, primary_key=True)
    embarazo_multiple = models.BooleanField()
    num_controles_prenatales = models.IntegerField()
    its = models.BooleanField()
    resultado = models.CharField(max_length=100, blank=True)
    tratamiento = models.CharField(max_length=100, blank=True)
    tp_vaginal = models.BooleanField()
    tp_cesarea = models.BooleanField()
    tp_institucional = models.BooleanField()
    otro_tipo_parto = models.CharField(max_length=100, blank=True)
    acompanamiento_parto = models.BooleanField()
    nombre_acompanante = models.CharField(max_length=100, blank=True)
    apellido_acompanante = models.CharField(max_length=100, blank=True)
    edad_gestacional_semanas = models.IntegerField()
    peso_al_nacer_gramos = models.FloatField()

class ControlDeSalud(models.Model):
    id_nino = models.ForeignKey(Nino, on_delete=models.CASCADE)
    fecha = models.DateField()
    edad = models.IntegerField()
    peso = models.FloatField()
    talla_cm = models.FloatField()
    pc_cm = models.FloatField()
    alimentacion_pd = models.BooleanField()
    alimentacion_ppl = models.BooleanField()
    hierro_vit_d = models.BooleanField()
    fecha_prox_consulta = models.DateField()
    circ_cintura_cm = models.FloatField()
    imc = models.FloatField()
    pas = models.FloatField()
    pad = models.FloatField()

class Vacunas(models.Model):
    id_nino = models.OneToOneField(Nino, on_delete=models.CASCADE, primary_key=True)
    bcg = models.BooleanField()
    pentavalente = models.BooleanField()
    polio = models.BooleanField()
    sarampion_rubeola_paperas = models.BooleanField()
    varicela = models.BooleanField()
    neumococo_13_v = models.BooleanField()
    hepatitis_a = models.BooleanField()
    triple_bacteriana_dpt = models.BooleanField()
    triple_bacteriana_acelular_dpat = models.BooleanField()
    vph = models.BooleanField()
    anti_influenza = models.BooleanField()
    edad_meses = models.IntegerField()
    edad_anios = models.IntegerField()
